export enum Role {
  ADMIN = 'ADMIN',
  DEPT_HEAD = 'DEPT_HEAD',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  RECEPTIONIST = 'RECEPTIONIST',
  PHARMACIST = 'PHARMACIST',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  PATIENT = 'PATIENT',
  ACCOUNTANT = 'ACCOUNTANT',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  CLINICIAN = 'CLINICIAN',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum BloodGroup {
  A_POSITIVE = 'A+',
  A_NEGATIVE = 'A-',
  B_POSITIVE = 'B+',
  B_NEGATIVE = 'B-',
  AB_POSITIVE = 'AB+',
  AB_NEGATIVE = 'AB-',
  O_POSITIVE = 'O+',
  O_NEGATIVE = 'O-',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CHECKED_IN = 'CHECKED_IN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum VisitType {
  CONSULTATION = 'CONSULTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  EMERGENCY = 'EMERGENCY',
  CHECKUP = 'CHECKUP',
  PROCEDURE = 'PROCEDURE',
}

export enum AdmissionStatus {
  PENDING = 'PENDING',
  ADMITTED = 'ADMITTED',
  DISCHARGED = 'DISCHARGED',
  TRANSFERRED = 'TRANSFERRED',
}

export enum RoomType {
  GENERAL = 'GENERAL',
  SEMI_PRIVATE = 'SEMI_PRIVATE',
  PRIVATE = 'PRIVATE',
  ICU = 'ICU',
  CCU = 'CCU',
  MATERNITY = 'MATERNITY',
  PEDIATRIC = 'PEDIATRIC',
  ER = 'ER',
  OBSERVATION = 'OBSERVATION',
}

export enum RoomStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  CLEANING = 'CLEANING',
  MAINTENANCE = 'MAINTENANCE',
  RESERVED = 'RESERVED',
}

export enum BedStatus {
  AVAILABLE = 'AVAILABLE',
  OCCUPIED = 'OCCUPIED',
  RESERVED = 'RESERVED',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}

export enum BillStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  WAIVED = 'WAIVED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  INSURANCE = 'INSURANCE',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
}

export enum PrescriptionStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  DISPENSED = 'DISPENSED',
  PARTIALLY_DISPENSED = 'PARTIALLY_DISPENSED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum MedicationForm {
  TABLET = 'TABLET',
  CAPSULE = 'CAPSULE',
  SYRUP = 'SYRUP',
  INJECTION = 'INJECTION',
  OINTMENT = 'OINTMENT',
  CREAM = 'CREAM',
  DROPS = 'DROPS',
  INHALER = 'INHALER',
  SUPPOSITORY = 'SUPPOSITORY',
  POWDER = 'POWDER',
}

export enum DrugCategory {
  ANTIBIOTIC = 'ANTIBIOTIC',
  ANALGESIC = 'ANALGESIC',
  ANTIHYPERTENSIVE = 'ANTIHYPERTENSIVE',
  ANTIDIABETIC = 'ANTIDIABETIC',
  ANTIVIRAL = 'ANTIVIRAL',
  ANTIFUNGAL = 'ANTIFUNGAL',
  CARDIOVASCULAR = 'CARDIOVASCULAR',
  RESPIRATORY = 'RESPIRATORY',
  GASTROINTESTINAL = 'GASTROINTESTINAL',
  VITAMIN = 'VITAMIN',
  VACCINE = 'VACCINE',
  OTHER = 'OTHER',
}

export enum LabTestStatus {
  PENDING = 'PENDING',
  SAMPLE_COLLECTED = 'SAMPLE_COLLECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REVIEWED = 'REVIEWED',
  CANCELLED = 'CANCELLED',
}

export enum LabSampleType {
  BLOOD = 'BLOOD',
  URINE = 'URINE',
  STOOL = 'STOOL',
  SPUTUM = 'SPUTUM',
  SALIVA = 'SALIVA',
  BIOPSY = 'BIOPSY',
  CSF = 'CSF',
  OTHER = 'OTHER',
}

export enum LabTestPriority {
  ROUTINE = 'ROUTINE',
  URGENT = 'URGENT',
  STAT = 'STAT',
}

export enum Department {
  CARDIOLOGY = 'CARDIOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  PEDIATRICS = 'PEDIATRICS',
  ORTHOPEDICS = 'ORTHOPEDICS',
  GYNECOLOGY = 'GYNECOLOGY',
  GENERAL_MEDICINE = 'GENERAL_MEDICINE',
  SURGERY = 'SURGERY',
  EMERGENCY = 'EMERGENCY',
  ONCOLOGY = 'ONCOLOGY',
  DERMATOLOGY = 'DERMATOLOGY',
  OPHTHALMOLOGY = 'OPHTHALMOLOGY',
  ENT = 'ENT',
  PSYCHIATRY = 'PSYCHIATRY',
  RADIOLOGY = 'RADIOLOGY',
  PATHOLOGY = 'PATHOLOGY',
  PHARMACY = 'PHARMACY',
  LABORATORY = 'LABORATORY',
  PHYSIOTHERAPY = 'PHYSIOTHERAPY',
}

export enum Shift {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  NIGHT = 'NIGHT',
  ROTATING = 'ROTATING',
}

export enum InvoiceType {
  CONSULTATION = 'CONSULTATION',
  LAB_TEST = 'LAB_TEST',
  PROCEDURE = 'PROCEDURE',
  HOSPITALIZATION = 'HOSPITALIZATION',
  PHARMACY = 'PHARMACY',
  ROOM = 'ROOM',
  OTHER = 'OTHER',
}

export enum DischargeStatus {
  RECOVERED = 'RECOVERED',
  IMPROVED = 'IMPROVED',
  REFERRED = 'REFERRED',
  LEFT_AGAINST_ADVICE = 'LEFT_AGAINST_ADVICE',
  DECEASED = 'DECEASED',
  TRANSFERRED = 'TRANSFERRED',
}

export enum Permission {
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_PATIENTS = 'MANAGE_PATIENTS',
  MANAGE_APPOINTMENTS = 'MANAGE_APPOINTMENTS',
  MANAGE_STAFF = 'MANAGE_STAFF',
  MANAGE_BILLING = 'MANAGE_BILLING',
  MANAGE_PHARMACY = 'MANAGE_PHARMACY',
  MANAGE_LAB = 'MANAGE_LAB',
  MANAGE_ROOMS = 'MANAGE_ROOMS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  MANAGE_REPORTS = 'MANAGE_REPORTS',
  MANAGE_MEDICAL_RECORDS = 'MANAGE_MEDICAL_RECORDS',
  VIEW_PATIENT_PROFILE = 'VIEW_PATIENT_PROFILE',
  MANAGE_OWN_SCHEDULE = 'MANAGE_OWN_SCHEDULE',
  MANAGE_OWN_PATIENTS = 'MANAGE_OWN_PATIENTS',
  DISPENSE_MEDICATION = 'DISPENSE_MEDICATION',
  ORDER_LAB_TESTS = 'ORDER_LAB_TESTS',
  ADMIT_PATIENTS = 'ADMIT_PATIENTS',
  DISCHARGE_PATIENTS = 'DISCHARGE_PATIENTS',
  CREATE_INVOICE = 'CREATE_INVOICE',
  PROCESS_PAYMENTS = 'PROCESS_PAYMENTS',
  VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS',
  MANAGE_PROGRAMS = 'MANAGE_PROGRAMS',
  MANAGE_WAVES = 'MANAGE_WAVES',
  MANAGE_CASES = 'MANAGE_CASES',
  REVIEW_APPEALS = 'REVIEW_APPEALS',
  REVIEW_ONBOARDING = 'REVIEW_ONBOARDING',
  ASSIGN_CASES = 'ASSIGN_CASES',
  APPLY_TO_CASES = 'APPLY_TO_CASES',
  MANAGE_OWN_PATIENT_PROFILE = 'MANAGE_OWN_PATIENT_PROFILE',
  MANAGE_OWN_APPOINTMENTS = 'MANAGE_OWN_APPOINTMENTS',
  SUBMIT_REVIEWS = 'SUBMIT_REVIEWS',
}

export enum NotificationType {
  INFO = 'info',
  SUCCESS = 'success',
  WARNING = 'warning',
  ERROR = 'error',
  URGENT = 'urgent',
}

export enum VitalType {
  TEMPERATURE = 'TEMPERATURE',
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  PULSE = 'PULSE',
  RESPIRATION = 'RESPIRATION',
  WEIGHT = 'WEIGHT',
  HEIGHT = 'HEIGHT',
  BMI = 'BMI',
  BLOOD_SUGAR = 'BLOOD_SUGAR',
  SPO2 = 'SPO2',
}

export enum CaseComplexity {
  TRIVIAL = 'TRIVIAL',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum CaseStatus {
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  ROLLED_OVER = 'ROLLED_OVER',
  CANCELLED = 'CANCELLED',
}

export enum WaveStatus {
  UPCOMING = 'UPCOMING',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum ProgramStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  ARCHIVED = 'ARCHIVED',
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  INACTIVE = 'INACTIVE',
  WITHDRAWN = 'WITHDRAWN',
}
